In [1]:
PATH = '../../data/2019/'

In [2]:
import pandas as pd
display.max_columns = 20

In [29]:
df = pd.read_csv(PATH + 'rodada-2.csv')
#df.drop(columns = "Unnamed: 0", inplace = True)

In [30]:
df.to_csv(PATH + 'rodada-2.csv', index = False)

In [31]:
df.columns

Index(['atletas.nome', 'atletas.slug', 'atletas.apelido', 'atletas.foto',
       'atletas.atleta_id', 'atletas.rodada_id', 'atletas.clube_id',
       'atletas.posicao_id', 'atletas.status_id', 'atletas.pontos_num',
       'atletas.preco_num', 'atletas.variacao_num', 'atletas.media_num',
       'atletas.clube.id.full.name', 'FC', 'FS', 'PE', 'RB', 'SG', 'CA', 'FF',
       'FD', 'G', 'I', 'A', 'GS', 'DD', 'FT', 'PP', 'CV', 'GC', 'DP'],
      dtype='object')

In [32]:
columns = ['Nome', 'Slug', 'Apelido', 'Foto', 'ID', 'Rodada', 'ClubeID', 'Posição', 'Status', 'Pontos', 'Preço', 
          'Variação', 'Media', 'Clube', 'FC', 'FS', 'PE', 'RB', 'SG', 'CA', 'FF','FD', 'G', 'I', 'A', 'GS', 'DD', 
           'FT', 'PP', 'CV', 'GC', 'DP']
df.columns = columns
df.columns

Index(['Nome', 'Slug', 'Apelido', 'Foto', 'ID', 'Rodada', 'ClubeID', 'Posição',
       'Status', 'Pontos', 'Preço', 'Variação', 'Media', 'Clube', 'FC', 'FS',
       'PE', 'RB', 'SG', 'CA', 'FF', 'FD', 'G', 'I', 'A', 'GS', 'DD', 'FT',
       'PP', 'CV', 'GC', 'DP'],
      dtype='object')

In [33]:
cols_scouts_def = ['CA','CV','DD','DP','FC','GC','GS','RB','SG'] # alphabetical order
cols_scouts_atk = ['A','FD','FF','FS','FT','G','I','PE','PP'] # alphabetical order
cols_scouts = cols_scouts_def + cols_scouts_atk

In [34]:
print("Dimensões originais dos dados: ", df.shape)

# remove todas as linhas cujo scouts são NANs 
df_clean = df.dropna(how='all', subset=cols_scouts)
print('qtde. de jogadores com scouts: ', df_clean.shape[0])

# remove técnicos e jogadores sem posição
df_clean = df_clean[(df_clean['Posição'] != "tec") & (~df_clean['Posição'].isnull())]
print("qtde. de linhas com posições válidas: ", df_clean.shape[0])

# atualiza nomes dos jogadores sem ids e remove jogadores sem nome
df_ids =  df.groupby('ID')['Apelido'].unique()
dict_ids = dict(zip(df_ids.index, [str(v[-1]) for v in df_ids.values]))
dict_ids = {k:v for k,v in dict_ids.items() if v != 'nan'}
df_clean['Apelido'] = df_clean['ID'].map(dict_ids)
df_clean = df_clean[~df_clean['Apelido'].isnull()]
print("qtde. de jogadores com nome: ", df_clean.shape[0])

# preenche NANs restantes com zeros (verificado antes!)
df_clean.fillna(value=0, inplace=True)

print("Dimensão dos dados após as limpezas: ", df_clean.shape)
df_clean.head(10)

Dimensões originais dos dados:  (738, 32)
qtde. de jogadores com scouts:  313
qtde. de linhas com posições válidas:  313
qtde. de jogadores com nome:  313
Dimensão dos dados após as limpezas:  (313, 32)

,Nome,Slug,Apelido,Foto,ID,Rodada,ClubeID,Posição,Status,Pontos,...,G,I,A,GS,DD,FT,PP,CV,GC,DP
0,Anderson Vital da Silva,dede,Dedé,https://s.glbimg.com/es/sde/f/2018/05/18/868bc...,60819,2,283,zag,Provável,10.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Pedro Tonon Geromel,pedro-geromel,Pedro Geromel,https://s.glbimg.com/es/sde/f/2018/05/21/afc76...,80853,2,284,zag,Nulo,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Luan Madson Gedeão De Paiva,luan,Luan,https://s.glbimg.com/es/sde/f/2018/05/07/c8caf...,63219,2,282,mei,Nulo,-0.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Bruno Henrique Pinto,bruno-henrique,Bruno Henrique,https://s.glbimg.com/es/sde/f/2019/04/26/195ab...,90285,2,262,ata,Nulo,-2.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Gabriel Barbosa Almeida,gabriel,Gabriel,https://s.glbimg.com/es/sde/f/2019/04/26/dd351...,83257,2,262,ata,Nulo,0.9,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Vinícius Goes Barbosa de Souza,vinicius,Vinícius,https://s.glbimg.com/es/sde/f/2019/03/29/188d8...,71162,2,282,mei,Nulo,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Geuvânio Santos Silva,geuvanio,Geuvânio,https://s.glbimg.com/es/sde/f/2019/03/25/6756f...,73896,2,282,ata,Provável,5.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Walter Kannemann,kannemann,Kannemann,https://s.glbimg.com/es/sde/f/2018/05/21/7a4b8...,87342,2,284,zag,Nulo,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Everton Sousa Soares,everton,Everton,https://s.glbimg.com/es/sde/f/2018/05/18/997fe...,86757,2,284,ata,Dúvida,-0.3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Renê Rodrigues Martins,rene,Renê,https://s.glbimg.com/es/sde/f/2019/04/26/f7f5e...,78445,2,262,lat,Nulo,-1.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df_clean.head(5)

,Nome,Slug,Apelido,Foto,ID,Rodada,ClubeID,Posição,Status,Pontos,...,FC,FD,A,I,SG,FT,CV,GC,DP,PP
0,Anderson Vital da Silva,dede,Dedé,https://s.glbimg.com/es/sde/f/2018/05/18/868bc...,60819,2,283,zag,Provável,10.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Pedro Tonon Geromel,pedro-geromel,Pedro Geromel,https://s.glbimg.com/es/sde/f/2018/05/21/afc76...,80853,2,284,zag,Nulo,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Luan Madson Gedeão De Paiva,luan,Luan,https://s.glbimg.com/es/sde/f/2018/05/07/c8caf...,63219,2,282,mei,Nulo,-0.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Bruno Henrique Pinto,bruno-henrique,Bruno Henrique,https://s.glbimg.com/es/sde/f/2019/04/26/195ab...,90285,2,262,ata,Nulo,-2.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Gabriel Barbosa Almeida,gabriel,Gabriel,https://s.glbimg.com/es/sde/f/2019/04/26/dd351...,83257,2,262,ata,Nulo,0.9,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
df_util = df_clean[['Apelido','Posição', 'Status', 'Pontos', 'Preço', 'Variação', 'Media', 'Clube', 'CA', 'FF', 'FS', 'G', 'PE', 'RB', 'DD', 'GS', 'FC', 'FD', 'A', 'I', 'SG', 
           'FT', 'CV', 'GC', 'DP', 'PP']]
df_util.head(5)

,Apelido,Posição,Status,Pontos,Preço,Variação,Media,Clube,CA,FF,...,FC,FD,A,I,SG,FT,CV,GC,DP,PP
0,Dedé,zag,Provável,10.6,14.95,0.80,5.50,Cruzeiro,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,Pedro Geromel,zag,Nulo,0.6,11.61,-0.88,4.30,Grêmio,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Luan,mei,Nulo,-0.4,6.69,-1.36,1.60,Atlético-MG,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Bruno Henrique,ata,Nulo,-2.0,20.77,-0.74,9.50,Flamengo,1.0,4.0,...,2.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Gabriel,ata,Nulo,0.9,16.91,-1.13,6.45,Flamengo,1.0,2.0,...,1.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
new_cols_scouts_atk = ['Apelido', 'Posição', 'Media', 'G','A','FD', 'FT', 'FF','FS','I','PE','PP'] # alphabetical order
pos = ['ata','mei']
df_ata_mei = df_clean[new_cols_scouts_atk][df_clean.Posição.isin(pos)]
df_ata_mei.head(20)

,Apelido,Posição,Media,G,A,FD,FT,FF,FS,I,PE,PP
3,Luan,mei,1.60,0.0,0.0,0.0,0.0,0.0,2.0,0.0,6.0,0.0
4,Bruno Henrique,ata,9.50,2.0,0.0,2.0,0.0,4.0,3.0,1.0,2.0,0.0
5,Gabriel,ata,6.45,1.0,0.0,3.0,0.0,2.0,4.0,2.0,6.0,0.0
6,Vinícius,mei,-0.50,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7,Geuvânio,ata,9.45,0.0,1.0,1.0,0.0,2.0,8.0,0.0,3.0,0.0
9,Everton,ata,5.15,1.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0
13,José Welison,mei,1.45,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0
15,Nathan,mei,1.20,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Jair,mei,1.75,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,Chará,ata,5.70,1.0,0.0,0.0,0.0,3.0,2.0,0.0,10.0,0.0
44,Jones Carioca,ata,1.15,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
46,Matheus Barbosa,mei,3.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0
52,André Moritz,mei,2.00,0.0,0.0,1.0,0.0,3.0,2.0,0.0,7.0,0.0
53,Paolo Guerrero,ata,12.00,1.0,0.0,1.0,0.0,2.0,2.0,1.0,1.0,0.0
55,D'Alessandro,mei,7.30,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0
56,Pedro Castro,mei,0.95,0.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0,0.0
58,Edenílson,mei,3.60,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
61,Rodrigo Lindoso,mei,2.90,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
62,Gegê,mei,-0.30,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
64,William Pottker,ata,2.30,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0

In [39]:
df_ata_mei['F'] = df_ata_mei['FF'] + df_ata_mei['G'] + df_ata_mei['FT'] + df_ata_mei['FD']
df_ata_mei.head()

,Apelido,Posição,Media,G,A,FD,FT,FF,FS,I,PE,PP,F
3,Luan,mei,1.60,0.0,0.0,0.0,0.0,0.0,2.0,0.0,6.0,0.0,0.0
4,Bruno Henrique,ata,9.50,2.0,0.0,2.0,0.0,4.0,3.0,1.0,2.0,0.0,8.0
5,Gabriel,ata,6.45,1.0,0.0,3.0,0.0,2.0,4.0,2.0,6.0,0.0,6.0
6,Vinícius,mei,-0.50,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
7,Geuvânio,ata,9.45,0.0,1.0,1.0,0.0,2.0,8.0,0.0,3.0,0.0,3.0

In [40]:
df_ata_mei.sort_values(['F'], ascending = False).head(15)

,Apelido,Posição,Media,G,A,FD,FT,FF,FS,I,PE,PP,F
4,Bruno Henrique,ata,9.50,2.0,0.0,2.0,0.0,4.0,3.0,1.0,2.0,0.0,8.0
5,Gabriel,ata,6.45,1.0,0.0,3.0,0.0,2.0,4.0,2.0,6.0,0.0,6.0
654,Marrony,ata,6.95,0.0,1.0,2.0,0.0,4.0,7.0,0.0,4.0,0.0,6.0
159,Ricardo Bueno,ata,8.90,2.0,1.0,2.0,0.0,1.0,1.0,2.0,3.0,1.0,5.0
655,Yan Sasse,mei,2.30,0.0,0.0,1.0,0.0,4.0,2.0,0.0,6.0,0.0,5.0
419,Edinho,mei,6.10,1.0,0.0,1.0,0.0,3.0,5.0,0.0,3.0,0.0,5.0
582,Nico López,ata,5.80,0.0,0.0,1.0,1.0,3.0,0.0,0.0,1.0,0.0,5.0
496,Jonatan Álvez,ata,3.90,0.0,0.0,1.0,0.0,4.0,0.0,1.0,0.0,0.0,5.0
538,Eduardo Sasha,ata,13.25,2.0,0.0,0.0,0.0,3.0,2.0,0.0,3.0,0.0,5.0
96,Nikão,mei,12.30,1.0,1.0,1.0,0.0,3.0,4.0,0.0,0.0,0.0,5.0
115,Arthur Caíke,ata,7.80,2.0,0.0,1.0,0.0,2.0,0.0,1.0,4.0,0.0,5.0
405,Luciano,ata,-0.75,0.0,0.0,2.0,0.0,3.0,6.0,2.0,6.0,1.0,5.0
281,Clayson,ata,6.00,1.0,0.0,3.0,0.0,1.0,2.0,0.0,8.0,0.0,5.0
622,Ricardo Oliveira,ata,7.05,1.0,0.0,1.0,1.0,2.0,1.0,0.0,4.0,0.0,5.0
213,Leandro Carvalho,ata,5.75,1.0,0.0,1.0,0.0,2.0,1.0,1.0,6.0,0.0,4.0

In [43]:
df_ata_mei['Efetividade'] = df_ata_mei['G'] / df_ata_mei['F']
df_ata_mei.sort_values(['Efetividade'], ascending = False).head(30)

,Apelido,Posição,Media,G,A,FD,FT,FF,FS,I,PE,PP,F,Efetividade
730,Pedro Rocha,ata,9.10,1.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,1.0,1.000000
707,Maxi López,ata,3.05,1.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0,1.000000
698,Bruno César,mei,7.50,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.000000
688,Romulo,mei,8.20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.000000
92,Brizuela,ata,4.70,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.000000
168,Erik,ata,7.45,1.0,1.0,0.0,0.0,0.0,7.0,0.0,7.0,0.0,1.0,1.000000
506,Sarrafiore,mei,3.25,1.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,1.0,1.000000
292,Pedrinho,mei,4.35,1.0,0.0,0.0,0.0,0.0,3.0,0.0,6.0,0.0,1.0,1.000000
585,Everton,mei,2.75,1.0,0.0,0.0,0.0,0.0,3.0,1.0,5.0,0.0,1.0,1.000000
141,Artur,ata,4.50,1.0,0.0,1.0,0.0,0.0,2.0,1.0,9.0,0.0,2.0,0.500000
351,Arrascaeta,mei,6.55,1.0,0.0,0.0,0.0,1.0,6.0,0.0,4.0,0.0,2.0,0.500000
424,Pedro,ata,4.60,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.500000
594,Hudson,mei,6.95,1.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.500000
574,Carlos Sánchez,mei,4.60,1.0,0.0,0.0,0.0,1.0,1.0,0.0,7.0,0.0,2.0,0.500000
642,Toró,ata,5.85,1.0,0.0,0.0,0.0,1.0,3.0,0.0,2.0,0.0,2.0,0.500000
674,Thiago Neves,mei,3.90,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0,0.500000
9,Everton,ata,5.15,1.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,2.0,0.500000
297,Everaldo,ata,8.55,2.0,0.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,4.0,0.500000
159,Ricardo Bueno,ata,8.90,2.0,1.0,2.0,0.0,1.0,1.0,2.0,3.0,1.0,5.0,0.400000
115,Arthur Caíke,ata,7.80,2.0,0.0,1.0,0.0,2.0,0.0,1.0,4.0,0.0,5.0,0.400000
538,Eduardo Sasha,ata,13.25,2.0,0.0,0.0,0.0,3.0,2.0,0.0,3.0,0.0,5.0,0.400000
243,Bruno Guimarães,mei,6.35,1.0,0.0,0.0,1.0,1.0,6.0,0.0,2.0,0.0,3.0,0.333333
451,Wellington Paulista,ata,6.60,1.0,0.0,1.0,0.0,1.0,4.0,0.0,1.0,0.0,3.0,0.333333
161,João Paulo,mei,6.65,1.0,0.0,2.0,0.0,0.0,4.0,0.0,7.0,0.0,3.0,0.333333
628,Elias,mei,8.55,1.0,0.0,0.0,1.0,1.0,3.0,0.0,4.0,0.0,3.0,0.333333
684,Alexandre Pato,ata,4.95,1.0,0.0,0.0,0.0,2.0,2.0,2.0,4.0,0.0,3.0,0.333333
152,Cícero,mei,10.50,1.0,1.0,1.0,0.0,1.0,9.0,0.0,5.0,0.0,3.0,0.333333
403,Matheus Savio,mei,7.00,1.0,0.0,1.0,1.0,0.0,1.0,0.0,4.0,0.0,3.0,0.333333
4,Bruno Henrique,ata,9.50,2.0,0.0,2.0,0.0,4.0,3.0,1.0,2.0,0.0,8.0,0.250000
213,Leandro Carvalho,ata,5.75,1.0,0.0,1.0,0.0,2.0,1.0,1.0,6.0,0.0,4.0,0.250000

In [44]:
new_cols_scouts_def = ['Apelido', 'Posição', 'Media', 'CA','CV','DD','DP','FC','GC','GS','RB','SG'] # alphabetical order
pos = ['def', 'lat', 'mei', 'ata']
df_def = df_clean[new_cols_scouts_def][df_clean.Posição.isin(pos)]
df_def.head(30)

,Apelido,Posição,Media,CA,CV,DD,DP,FC,GC,GS,RB,SG
3,Luan,mei,1.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0
4,Bruno Henrique,ata,9.50,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
5,Gabriel,ata,6.45,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0
6,Vinícius,mei,-0.50,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
7,Geuvânio,ata,9.45,0.0,0.0,0.0,0.0,5.0,0.0,0.0,7.0,0.0
9,Everton,ata,5.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,Renê,lat,-0.25,1.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
13,José Welison,mei,1.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
15,Nathan,mei,1.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Jair,mei,1.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
27,Chará,ata,5.70,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0
29,Guga,lat,3.40,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0
44,Jones Carioca,ata,1.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
46,Matheus Barbosa,mei,3.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0
52,André Moritz,mei,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
53,Paolo Guerrero,ata,12.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
55,D'Alessandro,mei,7.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
56,Pedro Castro,mei,0.95,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0
58,Edenílson,mei,3.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
61,Rodrigo Lindoso,mei,2.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
62,Gegê,mei,-0.30,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0
64,William Pottker,ata,2.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
71,Mosquera,mei,1.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,João Paulo,mei,1.95,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0
74,Getúlio,ata,4.70,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0
82,Luan Pereira,mei,1.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
86,Iury,lat,7.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0
90,Nilton,mei,1.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,Brizuela,ata,4.70,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
94,Jonathan,lat,0.80,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0

In [45]:
df_def['RB_SF'] = df_def['RB'] / df_def['FC']
df_def[df_def.FC != 0].sort_values(['RB_SF', 'RB'], ascending = False).head(50)

,Apelido,Posição,Media,CA,CV,DD,DP,FC,GC,GS,RB,SG,RB_SF
104,Fagner,lat,8.75,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,1.0,8.000000
277,Márcio Araújo,mei,6.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,7.0,0.0,7.000000
46,Matheus Barbosa,mei,3.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,5.000000
345,Willian Arão,mei,8.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,5.000000
259,Dawhan,mei,2.85,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
457,Giovanni Augusto,mei,1.90,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
524,Jefferson,lat,6.25,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,1.0,4.000000
534,Victor Ferraz,lat,1.80,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
678,Cuéllar,mei,6.80,0.0,0.0,0.0,0.0,3.0,0.0,0.0,10.0,0.0,3.333333
3,Luan,mei,1.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
330,Everton Ribeiro,mei,4.50,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
484,Claudio Winck,lat,4.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
712,Fellipe Bastos,mei,5.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
545,Rodrygo,ata,7.70,1.0,0.0,0.0,0.0,2.0,0.0,0.0,5.0,0.0,2.500000
126,Moisés,lat,7.70,0.0,0.0,0.0,0.0,3.0,0.0,0.0,7.0,0.0,2.333333
179,Gustavo Bochecha,mei,3.70,0.0,0.0,0.0,0.0,3.0,0.0,0.0,6.0,0.0,2.000000
278,Ramiro,mei,7.30,0.0,0.0,0.0,0.0,3.0,0.0,0.0,6.0,0.0,2.000000
29,Guga,lat,3.40,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
161,João Paulo,mei,6.65,1.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
401,Bruno Silva,mei,4.05,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
480,Zeca,lat,2.70,1.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
613,Matheus Henrique,mei,2.10,1.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
628,Elias,mei,8.55,0.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,2.000000
5,Gabriel,ata,6.45,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
86,Iury,lat,7.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
170,Samuel Xavier,lat,6.40,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,2.000000
213,Leandro Carvalho,ata,5.75,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
325,Robinho,mei,4.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
327,Diego,mei,0.80,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
351,Arrascaeta,mei,6.55,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
363,Madson,mei,3.05,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
394,Airton,mei,0.40,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
403,Matheus Savio,mei,7.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
442,Marcinho,ata,3.25,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
475,Neilton,ata,5.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
531,Alisson,mei,2.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
578,Maicon,mei,6.80,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
608,Jean Pyerre,mei,4.70,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
629,Nino Paraíba,lat,2.20,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,2.000000
96,Nikão,mei,12.30,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,1.666667
185,Fabinho,mei,2.55,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,1.666667
335,Pará,lat,1.70,1.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,1.666667
493,Reinaldo,lat,4.30,1.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,1.0,1.666667
504,Léo Sena,mei,1.90,1.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,1.666667
463,Geovane,mei,1.70,0.0,0.0,0.0,0.0,4.0,0.0,0.0,6.0,0.0,1.500000
73,João Paulo,mei,1.95,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,1.500000
241,Régis,mei,2.50,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,1.500000
244,Tharlis,mei,2.90,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,1.500000
432,Yony González,ata,3.05,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,1.500000
438,Felipe,mei,5.40,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,1.500000

In [46]:
df_def['RB_SF'] = df_def['RB'] / df_def['FC']
df_def.sort_values(['RB_SF', 'RB'], ascending = False).head(50)

,Apelido,Posição,Media,CA,CV,DD,DP,FC,GC,GS,RB,SG,RB_SF
254,Ralf,mei,6.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,inf
208,Bruno Pacheco,lat,8.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,inf
200,Fernando Sobral,mei,2.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,inf
510,Kevin,lat,4.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,inf
624,Adilson,mei,4.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,inf
687,Patrick,mei,4.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,inf
723,Eduardo,lat,4.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,inf
13,José Welison,mei,1.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
18,Jair,mei,1.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
151,Ramires,mei,5.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
152,Cícero,mei,10.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
315,Rafinha,mei,2.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
372,Didira,mei,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
449,Araruna,mei,0.40,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
471,Guilherme Parede,ata,4.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
686,Antony,ata,8.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,inf
9,Everton,ata,5.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
44,Jones Carioca,ata,1.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
52,André Moritz,mei,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
55,D'Alessandro,mei,7.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
61,Rodrigo Lindoso,mei,2.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
64,William Pottker,ata,2.30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
82,Luan Pereira,mei,1.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
187,Wenderson,mei,2.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
309,Robinho,ata,0.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
370,Armero,lat,0.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
382,Camilo,mei,3.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
441,Marlon,mei,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
466,Diego Tardelli,ata,1.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
501,Yago Pikachu,mei,1.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
559,Maicon,ata,7.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
582,Nico López,ata,5.80,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
584,Thaciano,mei,0.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
652,Andrey,mei,1.70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
674,Thiago Neves,mei,3.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
677,Rodriguinho,mei,2.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
735,Vitor Bueno,mei,1.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,inf
104,Fagner,lat,8.75,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,1.0,8.000000
277,Márcio Araújo,mei,6.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,7.0,0.0,7.000000
46,Matheus Barbosa,mei,3.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,5.000000
345,Willian Arão,mei,8.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,5.000000
259,Dawhan,mei,2.85,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
457,Giovanni Augusto,mei,1.90,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
524,Jefferson,lat,6.25,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,1.0,4.000000
534,Victor Ferraz,lat,1.80,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,4.000000
678,Cuéllar,mei,6.80,0.0,0.0,0.0,0.0,3.0,0.0,0.0,10.0,0.0,3.333333
3,Luan,mei,1.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
330,Everton Ribeiro,mei,4.50,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
484,Claudio Winck,lat,4.20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000
712,Fellipe Bastos,mei,5.30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,3.000000